language: python
python:
  - 3.4
branches:
  only:
    - master
addons:
  postgresql: "9.4"
install:
  - pip install -r requirements.txt
  - pip install sphinx sphinx_rtd_theme
before_script:
  - psql -U postgres -c "CREATE ROLE corvid PASSWORD 'password' NOSUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;"
  - echo "SECRET_KEY='test'" > corvid/corvid/credentials.py
  - echo "DB_PASSWORD='password'" >> corvid/corvid/credentials.py
script: cd corvid && python manage.py test
after_success:
  - cd .. && make -C doc html
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./push.sh || false'
env:
  global:
    - secure: "TQGw0WbTUw6L9kXvxLZmhmXZ6MZQtkxZWBAeJcKqQujGtoPXQLtcFz84co12y2P8B1NA2KLymEVT+NnyCveigSVgBn6noh+5yWWq2jflsZVdMCJK+LHDDmQ2p65ExSxqBKfEUW5l1V4NhLT8KgISG0woXFrR+iZj0Ydra6xTOJgLnj+/24afhewBK+KWEKUscjTYO5AXwnWwscKmZb9ECopDZIgVnmqZGiPUMM9+VUD+zfN/4d2YfsBz0ytm3Jj4MJAQjoM5fzJb+H0V1wo1jL+gpVq5tXAwHY/WyA2R5nX0wBP7HObpRzwysh3NYZPeaCxdxKAOMxo8UqnIUaocAThhe7u0HXyADP7q1CfLhSgJd2mwTs62XR5Q0KRecuo/VJdVcqOdGCR7ln6kfcc0WCxr+srhOcjDhQkYiEBrNKpQfDeof//7Z91Ec0YEknpOl5Lz9CYbYrbQZ536YfcmuEYzw9oexvFxz/DwwOhhJXquqW3Hyqqabh/QB7JjGpo34Iis3w09SvpJ56JxZ9unbJspvIx+X55S8ye2fA95B3xG+ssaJKGvP6QXcWM/geoO2+6MRirnKE660PgwevrZw/lcUMu8/Zggqp//LeAapTrVr7iCrfD6imOD6Aj9iDmmgWMxtByyJ6AWdaRdFC35eJm87ptBsF2JcYVozM1eI8Y="
