language: python
python:
  - 3.4
branches:
  only:
    - master
addons:
  postgresql: "9.4"
install:
  - pip install -r requirements.txt
  - pip install sphinx sphinx_rtd_theme
before_script:
  - psql -U postgres -c "CREATE ROLE fugl PASSWORD 'password' NOSUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;"
  - echo "SECRET_KEY='test'" > fugl/fugl/credentials.py
  - echo "DB_PASSWORD='password'" >> fugl/fugl/credentials.py
script: cd fugl && coverage run --source=fugl,main --omit=\*/migrations/\*,\*/management/\*,fugl/wsgi.py manage.py test
after_success:
  - pwd
  - coverage html -d ../htmlcov
  - cd .. && make -C doc html
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./push.sh || false'
env:
  global:
    - secure: "QBaR50Bck2q5AUHu3HOWvf3zNhD/JOb6+Pf2oISPNSWy5n2K8xeY3S2TpZ1Cmv7ovJaRWCtXfnac9A7Ilsa03nGmoP2a585bAfeapLdXVlQoXYHwd+7w5qnAmTtopPO4QE1A2gzu8XwjP0XyX22QJEnGbq3az7uLZh5TEVALpYMVzxfJDljDZUYZEtt1qRm2IVjQmIHarVYDes0Aa+E52VD8y1VcKC1LK7+rcFx8g5+lH/59UE7aXLc5y+vS+GNVzsCERkMr6Qx0l0N+MMhJFoZdxn2zjSloi8v/0o+jA1tQInfRWCC4yN+0ykCLM+hw11Ld3BLmpWtC3EA+9KptdaPn2YCvnMFfAlQOEIGXsCQjmceM0w+WPkpumebtEMfYjsqJDIir3l9r4qV+hNtGJEQ6jN/9ceTGWfXN4g294PWvygD/6G8OD+iBY9lNSvC9A9sdupD2eJNyye37tGwE/kWQvI7ojFHev+gKJwXqgHy5AfO10F9IpVo9iWr9T70gJO9KZjdDHT/QIkk6EXChFwc92xuCLjrh+SLsn6I6jFQzyFsBgLEv9FjlmAZxlD8EkmQcaav7MXyUJ5uq4K/ty+uDBbbnRMDL/Daxbjo9UQJh1tgJ+clPEuo8vft9qWknfYRCEntSsj9N41llui6dpjPY9YrUO+byoLgka1HbMzg="
